{
 "title": "Flink Nexmark Overview",
 "tags": [
  "flink",
  "nexmark"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(flink_jobmanager_job_lastCheckpointDuration{cluster=\"nexmark-flink\"}, job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MISS Amplification (ROCKSDB_MISSES / FLINK_GET_COUNT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum by (job_id, operator_id, operator_name, subtask_index) (\n    increase(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[15m])\n  )\n)\n/\nsum by (job_id, operator_id, operator_name, subtask_index) (\n  10*increase(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count[15m])\n)\n",
     "legendFormat": "read amplification factor"
    }
   ]
  },
  {
   "title": "HIT Amplification (ROCKSDB_HITS / FLINK_GET_COUNT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum by (job_id, operator_id, operator_name, subtask_index) (\n    increase(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[15m])\n  )\n)\n/\nsum by (job_id, operator_id, operator_name, subtask_index) (\n  10*increase(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count[15m])\n)\n",
     "legendFormat": "read amplification factor"
    }
   ]
  },
  {
   "title": "Read Amplification (ROCKSDB_ACCESSES / FLINK_GET_COUNT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum by (job_id, operator_id, operator_name, subtask_index) (\n    increase(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[15m])\n    + increase(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[15m])\n  )\n)\n/\nsum by (job_id, operator_id, operator_name, subtask_index) (\n  10*increase(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count[15m])\n)\n",
     "legendFormat": "read amplification factor"
    }
   ]
  },
  {
   "title": "Flink Level State Access Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Source Datagen and Egress Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\", operator_name=~\".*Source.*\"})",
     "legendFormat": "{{job_name}} Source Output"
    },
    {
     "expr": "avg_over_time(\n  sum by (job_name, operator_name) (\n    flink_taskmanager_job_task_operator_numRecordsOutPerSecond{\n      cluster=\"nexmark-flink\",\n      job_name=~\"$job\",\n      operator_name=~\".*Source.*\"\n    }\n  )[20m:]\n)",
     "legendFormat": "{{job_name}} smoothed throughput"
    }
   ]
  },
  {
   "title": "Block Cache Data Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m])) / (sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m])) + sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m])))) * 100",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    },
    {
     "expr": "(\n  sum without(instance, taskmanager_id) (\n    increase(\n      flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit{\n        cluster=\"nexmark-flink\",\n        job_name=~\"$job\"\n      }[20m]\n    )\n  )\n)\n/\n(\n  sum without(instance, taskmanager_id) (\n    increase(\n      flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit{\n        cluster=\"nexmark-flink\",\n        job_name=~\"$job\"\n      }[20m]\n    )\n  )\n  +\n  sum without(instance, taskmanager_id) (\n    increase(\n      flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss{\n        cluster=\"nexmark-flink\",\n        job_name=~\"$job\"\n      }[20m]\n    )\n  )\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (\n  max by (job_name, operator_name, subtask_index) (\n    flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage{cluster=\"nexmark-flink\", job_name=~\"$job\"}\n  )\n)",
     "legendFormat": "{{job_name}} - {{operator_name}} - Usage"
    },
    {
     "expr": "sum by (job_name, operator_name) (\n  max by (job_name, operator_name, subtask_index) (\n    flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_capacity{cluster=\"nexmark-flink\", job_name=~\"$job\"}\n  )\n)",
     "legendFormat": "{{job_name}} - {{operator_name}} - {{subtask_index}} Capacity"
    },
    {
     "expr": "sum by (job_name, operator_name) (\n  max by (job_name, operator_name, subtask_index) (\n    flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_pinned_usage{cluster=\"nexmark-flink\", job_name=~\"$job\"}\n  )\n)",
     "legendFormat": "{{job_name}} - {{operator_name}} - Pinned"
    }
   ]
  },
  {
   "title": "Block Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]) / (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]) + rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m]))",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    },
    {
     "expr": "(\n  sum without(instance, taskmanager_id) (\n    increase(\n      flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{\n        cluster=\"nexmark-flink\",\n        job_name=~\"$job\"\n      }[20m]\n    )\n  )\n)\n/\n(\n  sum without(instance, taskmanager_id) (\n    increase(\n      flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{\n        cluster=\"nexmark-flink\",\n        job_name=~\"$job\"\n      }[20m]\n    )\n  )\n  +\n  sum without(instance, taskmanager_id) (\n    increase(\n      flink_taskmanager_job_task_operator_rocksdb_block_cache_miss{\n        cluster=\"nexmark-flink\",\n        job_name=~\"$job\"\n      }[20m]\n    )\n  )\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput & Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Source Datagen and Egress Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\", operator_name=~\".*Source.*\"})",
     "legendFormat": "{{job_name}} Source Output"
    },
    {
     "expr": "quantile_over_time(0.5,\n  sum by (job_name, operator_name) (\n    flink_taskmanager_job_task_operator_numRecordsOutPerSecond{\n      cluster=\"nexmark-flink\", \n      job_name=~\"$job\", \n      operator_name=~\".*Source.*\"\n    }\n  )[20m:]\n)",
     "legendFormat": "{{job_name}} smoothed throughput"
    }
   ]
  },
  {
   "title": "Operator RecordsIn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_numRecordsInPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Operator RecordsOut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  { "title": "Task Thread Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Task Thread Backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job_name, task_name) (flink_taskmanager_job_task_backPressuredTimeMsPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\"}) / 10",
     "legendFormat": "{{job_name}} {{task_name}}"
    }
   ]
  },
  {
   "title": "Task Thread Busy vs Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job_name, task_name) (flink_taskmanager_job_task_busyTimeMsPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\"}) / 10",
     "legendFormat": "{{job_name}} {{task_name}} - Busy %"
    },
    {
     "expr": "avg by (job_name, task_name) (flink_taskmanager_job_task_idleTimeMsPerSecond{cluster=\"nexmark-flink\", job_name=~\"$job\"}) / 10",
     "legendFormat": "{{job_name}} {{task_name}} - Idle %"
    }
   ]
  },
  { "title": "TaskManager Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "TaskManager CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (host) (flink_taskmanager_Status_JVM_CPU_Load{cluster=\"nexmark-flink\"}) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heap vs Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host) (flink_taskmanager_Status_JVM_Memory_Heap_Used{cluster=\"nexmark-flink\"})",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "sum by (host) (flink_taskmanager_Status_JVM_Memory_NonHeap_Used{cluster=\"nexmark-flink\"})",
     "legendFormat": "Non-Heap Used"
    },
    {
     "expr": "sum by (host) (flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{cluster=\"nexmark-flink\"})",
     "legendFormat": "Direct Used"
    }
   ]
  },
  {
   "title": "Network Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum by (host) (flink_taskmanager_Status_Network_AvailableMemorySegments{cluster=\"nexmark-flink\"}) / sum by (host) (flink_taskmanager_Status_Network_TotalMemorySegments{cluster=\"nexmark-flink\"})) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "RocksDB State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Block Cache Accesses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_hit + flink_taskmanager_job_task_operator_rocksdb_block_cache_miss",
     "legendFormat": "total accesses"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_hit",
     "legendFormat": "num hits"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_miss",
     "legendFormat": "num misses"
    }
   ]
  },
  {
   "title": "Block Cache Accesses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit + flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss",
     "legendFormat": "total accesses"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit",
     "legendFormat": "num hits"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss",
     "legendFormat": "num misses"
    }
   ]
  },
  {
   "title": "Block Cache Acces Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m])) + \nsum(rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m]))",
     "legendFormat": "access rate"
    },
    {
     "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m])",
     "legendFormat": "hit rate"
    },
    {
     "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m])",
     "legendFormat": "miss rate"
    }
   ]
  },
  {
   "title": "Index Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_index_miss",
     "legendFormat": "access rate"
    }
   ]
  },
  {
   "title": "Block Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]) / (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]) + rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m]))",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Block Cache Data Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m])) / (sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m])) + sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m])))) * 100",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Block Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (\n  max by (job_name, operator_name, subtask_index) (\n    flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage{cluster=\"nexmark-flink\", job_name=~\"$job\"}\n  )\n)",
     "legendFormat": "{{job_name}} - {{operator_name}} - Usage"
    },
    {
     "expr": "sum by (job_name, operator_name) (\n  max by (job_name, operator_name, subtask_index) (\n    flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_capacity{cluster=\"nexmark-flink\", job_name=~\"$job\"}\n  )\n)",
     "legendFormat": "{{job_name}} - {{operator_name}} - {{subtask_index}} Capacity"
    },
    {
     "expr": "sum by (job_name, operator_name) (\n  max by (job_name, operator_name, subtask_index) (\n    flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_pinned_usage{cluster=\"nexmark-flink\", job_name=~\"$job\"}\n  )\n)",
     "legendFormat": "{{job_name}} - {{operator_name}} - Pinned"
    }
   ]
  },
  {
   "title": "Size All Memtables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name, column_family) (flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "{{job_name}} - {{column_family}}"
    }
   ]
  },
  {
   "title": "Live SST file size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job_name,operator_name) (flink_taskmanager_job_task_operator_column_family_rocksdb_live_sst_files_size{cluster=\"nexmark-flink\", job_name=~\"$job\"}) ",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Estimated Live Data size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job_name,operator_name) (flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_live_data_size{cluster=\"nexmark-flink\", job_name=~\"$job\"}) ",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Estimate Num Keys in DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "sum by (job_name,operator_name) (flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_num_keys{cluster=\"nexmark-flink\", job_name=~\"$job\"}) ",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  { "title": "State I/O & Background Work", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "RocksDB BLOCK CACHE Bytes Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_bytes_read{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m]))",
     "legendFormat": "Bytes Read From BLOCK CACHE - {{operator_name}} ({{job_name}})"
    },
    {
     "expr": "sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_bytes_write{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m]))",
     "legendFormat": "Bytes Written To BLOCK CACHE - {{operator_name}} ({{job_name}})"
    }
   ]
  },
  {
   "title": "RocksDB Bytes Read/Write (SST/Storage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_bytes_read{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m]))",
     "legendFormat": "Bytes Read From SST - {{operator_name}} ({{job_name}})"
    },
    {
     "expr": "sum by (job_name, operator_name) (rate(flink_taskmanager_job_task_operator_rocksdb_bytes_written{cluster=\"nexmark-flink\", job_name=~\"$job\"}[1m]))",
     "legendFormat": "Bytes Written to SST - {{operator_name}} ({{job_name}})"
    }
   ]
  },
  {
   "title": "Compaction IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_rocksdb_compact_read_bytes{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "Compaction Read - {{operator_name}} ({{job_name}})"
    },
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_rocksdb_compact_write_bytes{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "Compaction Write - {{operator_name}} ({{job_name}})"
    }
   ]
  },
  {
   "title": "Compaction Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (job_name, operator_name) (flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_pending_compaction_bytes{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "Compaction Bytes Pending - {{operator_name}} ({{job_name}})"
    }
   ]
  },
  { "title": "Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Last Checkpoint Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (job_name) (flink_jobmanager_job_lastCheckpointDuration{cluster=\"nexmark-flink\", job_name=~\"$job\"}) / 1000",
     "legendFormat": "Duration - {{job_name}}"
    }
   ]
  },
  {
   "title": "Checkpoint Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (job_name) (flink_jobmanager_job_lastCheckpointSize{cluster=\"nexmark-flink\", job_name=~\"$job\"})",
     "legendFormat": "Size - {{job_name}}"
    }
   ]
  }
 ]
}