FROM 142.150.234.180:5000/flink-justin:options-factory

# Copy nexmark JARs to Flink lib directory
COPY nexmark-flink-0.3-SNAPSHOT.jar /opt/flink/lib/

COPY rocksdb-options-1.0-SNAPSHOT.jar /opt/flink/lib/
COPY rocksdb-options-1.0-SNAPSHOT.jar /opt/flink/examples/justin/
